wandb:
  enabled: true  # Enables or disables Weights & Biases (WandB) logging.
  project: "RLFoundations"  # Name of the WandB project where logs and metrics will be stored.
  entity: null  # WandB entity (team/user) that owns the project. If null, defaults to the user's account.
  group: ${agent.algo}_${env.name}  # Groups runs by agent algorithm and environment name for better organization.
  name: "${experiment_name}_${now:%Y-%m-%d_%H-%M-%S}"  # Generates a unique run name using experiment name and timestamp.
  tags: ["${env.name}", "${agent.algo}"]  # Tags for organizing runs in WandB, based on environment and algorithm used.
  monitor_gym: true  # If true, logs Gym environment statistics (e.g., episode rewards, lengths).
  save_code: false  # Saves the script/code files to WandB for reproducibility.

checkpoint:
  enabled: false # Enables saving model checkpoints during training.
  save_freq: 50000  # Saves a checkpoint every 50,000 training steps.
  save_replay_buffer: true  # Saves the replay buffer (if applicable) to allow resuming training with past experiences.
  keep_best: true  # Retains the best-performing model checkpoint based on evaluation metrics.

tensorboard:
  enabled: true  # Enables TensorBoard logging if set to true.
  log_dir: ${paths.tensorboard_dir}  # Path where TensorBoard logs will be stored for visualization.