# conf/config.yaml
defaults:
  - agent: drl/sac # default agent
  - experiment: train
  - _self_

# Agent configuration
type: drl
algo: sac

# HER configuration
her:
  enabled: true # Set to true to enable HER
  n_sampled_goal: 4
  goal_selection_strategy: "future"

env:
  name: FetchPickAndPlace-v3
  max_episode_steps: 50

training:
  total_timesteps: 1000000
  eval_freq: 10000
  n_eval_episodes: 10

evaluation:
  deterministic: true
  record_freq: 5000
  videos_per_eval: 3
  save_metrics: true

logging:
  log_interval: 1000
  wandb: false
