# conf/config.yaml
defaults:
  - agent: drl/sac # default agent
  - experiment: train
  - logging: default
  - _self_

# Agent configuration
type: drl
algo: sac

# HER configuration
her:
  enabled: true # Set to true to enable HER
  n_sampled_goal: 32
  goal_selection_strategy: "future"

env:
  name: FetchPickAndPlace-v4
  max_episode_steps: 100

training:
  total_timesteps: 5000000
  eval_freq: 10000
  n_eval_episodes: 10

evaluation:
  deterministic: true
  record_freq: 10 # Record every 10 episodes
  save_metrics: true
