defaults:
  - common/paths@paths
  - common/logging@logging
  - common/training@training
  - common/evaluation@evaluation
  - env: fetch_pick
  - agent: il/bc
  - _self_

version_base: "1.3"
experiment_name: ${agent.algo}_${env.name}
type: ${agent.il.type}

# Dataset configuration
dataset:
  name: "FetchPickAndPlace-v4_sac_100"
  repo_id: "AOS55/FetchPickAndPlace-v4_sac_100"
  local_path: ${paths.demos_dir}/${dataset.name}

# BC-specific configurations
agent:
  algo: bc
  il:
    type: il
    algo: bc
    training:
      batch_size: 256
      n_epochs: 50
