defaults:
  - il/base
  - _self_

algo: "bc"
_target_: imitation.algorithms.bc.BC

bc:
  learning_rate: 1e-3
  batch_size: ${training.batch_size}
  n_epochs: ${training.n_epochs}
  policy_kwargs:
    net_arch: ${network.net_arch}
    activation_fn: ${network.activation}

dataset:
  name: null
  n_episodes: ${demos.n_episodes}
  path: ${demos.path}