defaults:
  - drl/base
  - _self_

algo: sac
_target_: stable_baselines3.SAC

sac:
  learning_rate: 3e-4
  batch_size: 256
  buffer_size: ${agent.drl.buffer.size}       
  learning_starts: ${agent.drl.buffer.learning_starts}
  ent_coef: "auto"
  train_freq: 1
  gradient_steps: 1
  tau: ${agent.drl.training.tau}            
  gamma: ${agent.drl.training.gamma}          
  policy_kwargs:
    net_arch: ${agent.drl.network.net_arch}    
    activation_fn: ${agent.drl.network.activation} 