_target_: stable_baselines3.SAC
policy: "MultiInputPolicy"
learning_rate: 3e-4
buffer_size: 1000000
learning_starts: 100
batch_size: 256
tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 1
ent_coef: "auto"
# policy_kwargs:
#   net_arch:
#     pi: [256, 256]
#     qf: [256, 256]
