_target_: stable_baselines3.TD3
policy: "MultiInputPolicy"
learning_rate: 1e-3
buffer_size: 1000000
learning_starts: 100
batch_size: 100
tau: 0.005
gamma: 0.99
train_freq: 1
policy_delay: 2
target_policy_noise: 0.2
target_noise_clip: 0.5
policy_kwargs:
  net_arch:
    pi: [400, 300]
    qf: [400, 300]
